name: "funpay"
services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    ports:
      - "33306:3306"
    volumes:
      - ./:/app
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - funpay
  php:
    build: docker/
    container_name: php
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    networks:
      - funpay
networks:
  funpay:
    name: funpay
    driver: bridge

volumes:
  mariadb-data:
    driver: local
